source 'http://rubygems.org'

gem 'bson_ext'
gem 'carrierwave'
gem 'ckeditor', :git => 'git@github.com:Bantik/rails-ckeditor.git', :branch => 'rails3_mongoid'
gem 'mongoid', '>= 2.0.0.beta.17'
gem 'mongoid-tree', :require => 'mongoid/tree'
gem 'rails', '>= 3.0.1'
gem 'rmagick'
gem 'site_logic', :path => '~/Documents/projects/site_logic'

group :development, :test do
  gem 'be_valid_asset'
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'cucumber'
  gem 'database_cleaner'
  gem 'faker'
  gem 'jeweler'
  gem 'launchy'
  gem 'machinist_mongo', :require => 'machinist/mongoid'
  gem 'mocha'
  gem 'rspec-rails'
  gem 'scaffold_logic', :git => 'git@github.com:Bantik/ScaffoldLogic.git'
  gem 'spork'
end
