# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "site_logic"
  s.version = "1.9.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bantik"]
  s.date = "2012-01-12"
  s.description = "An engine for search-engine-optimized content management."
  s.email = "corey@seologic.com"
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/nav_items_controller.rb",
    "app/controllers/admin/pages_controller.rb",
    "app/controllers/admin/redirects_controller.rb",
    "app/controllers/admin/sites_controller.rb",
    "app/controllers/application_controller.rb",
    "app/controllers/pages_controller.rb",
    "app/controllers/redirects_controller.rb",
    "app/helpers/layout_helper.rb",
    "app/models/ckeditor/asset.rb",
    "app/models/ckeditor/attachment_file.rb",
    "app/models/ckeditor/picture.rb",
    "app/models/nav_item.rb",
    "app/models/page.rb",
    "app/models/redirect.rb",
    "app/models/site.rb",
    "app/uploaders/image_uploader.rb",
    "app/views/admin/nav_items/_form.html.erb",
    "app/views/admin/nav_items/_index.html.erb",
    "app/views/admin/nav_items/_tabs.html.erb",
    "app/views/admin/nav_items/edit.html.erb",
    "app/views/admin/nav_items/index.html.erb",
    "app/views/admin/nav_items/new.html.erb",
    "app/views/admin/nav_items/show.html.erb",
    "app/views/admin/pages/_form.html.erb",
    "app/views/admin/pages/_index.html.erb",
    "app/views/admin/pages/edit.html.erb",
    "app/views/admin/pages/index.html.erb",
    "app/views/admin/pages/new.html.erb",
    "app/views/admin/pages/preview.html.erb",
    "app/views/admin/pages/show.html.erb",
    "app/views/admin/redirects/_form.html.erb",
    "app/views/admin/redirects/_index.html.erb",
    "app/views/admin/redirects/edit.html.erb",
    "app/views/admin/redirects/index.html.erb",
    "app/views/admin/redirects/new.html.erb",
    "app/views/admin/redirects/show.html.erb",
    "app/views/admin/sites/_form.html.erb",
    "app/views/admin/sites/edit.html.erb",
    "app/views/admin/sites/index.html.erb",
    "app/views/admin/sites/new.html.erb",
    "app/views/admin/sites/show.html.erb",
    "app/views/layouts/application.html.erb",
    "app/views/nav_items/_navigation.html.erb",
    "app/views/pages/show.html.erb",
    "app/views/shared/_nav_tabs.html.erb",
    "config.ru",
    "config/application.rb",
    "config/boot.rb",
    "config/cucumber.yml",
    "config/environment.rb",
    "config/environments/test.rb",
    "config/initializers/formats.rb",
    "config/initializers/metric_fu.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/session_store.rb",
    "config/mongoid.yml",
    "config/routes.rb",
    "doc/TODO",
    "features/manage_sites.feature",
    "features/step_definitions/general_steps.rb",
    "features/step_definitions/site_steps.rb",
    "features/step_definitions/web_steps.rb",
    "features/support/env.rb",
    "features/support/hooks.rb",
    "features/support/paths.rb",
    "lib/site_logic.rb",
    "lib/site_logic/navigation.rb",
    "lib/site_logic/railtie.rb",
    "lib/tasks/cucumber.rake",
    "public/images/icons/add.png",
    "public/images/icons/collapsed.gif",
    "public/images/icons/delete.png",
    "public/images/icons/drag.png",
    "public/images/icons/edit.png",
    "public/images/icons/expanded.gif",
    "public/images/icons/help_icon.png",
    "public/images/icons/link_icon.png",
    "public/images/icons/move.png",
    "public/images/icons/move_white.png",
    "public/images/icons/note.png",
    "public/images/icons/note_white.png",
    "public/images/icons/notification_icon_sprite.png",
    "public/images/icons/spinner.gif",
    "public/images/icons/view.png",
    "public/images/icons/warning.png",
    "public/images/icons/warning_2.png",
    "public/images/icons/warning_box.png",
    "public/images/icons/warning_icon.png",
    "public/images/icons/warning_white.png",
    "public/images/layout/arrow_asc.png",
    "public/images/layout/arrow_desc.png",
    "public/images/layout/back.png",
    "public/images/layout/black_bar.png",
    "public/images/layout/branding.png",
    "public/images/layout/breadcrumb_bg.png",
    "public/images/layout/button_bg.png",
    "public/images/layout/content_left_bg.png",
    "public/images/layout/content_right_bg.png",
    "public/images/layout/footer_bg.png",
    "public/images/layout/h1_bg.png",
    "public/images/layout/h2_bg.png",
    "public/images/layout/h2_bg_for_table.png",
    "public/images/layout/header_bg_grey.png",
    "public/images/layout/header_bg_purple.png",
    "public/images/layout/legend_bg.png",
    "public/images/layout/menu_box_bg.png",
    "public/images/layout/shadow_border.png",
    "public/images/layout/shadow_border_2.png",
    "public/images/layout/shadow_border_3.png",
    "public/images/layout/shadow_border_4.png",
    "public/images/layout/tab.png",
    "public/images/layout/tab_active.png",
    "public/images/layout/table_header.png",
    "public/images/layout/text_field_bg.jpg",
    "public/images/layout/text_field_error_bg.png",
    "public/images/layout/th_bg.png",
    "public/images/layout/th_bg_selected.png",
    "public/index.html",
    "public/stylesheets/.gitkeep",
    "public/stylesheets/application.css",
    "public/stylesheets/core.css",
    "script/cucumber",
    "script/rails",
    "site_logic.gemspec",
    "spec/blueprints.rb",
    "spec/controllers/admin/pages_controller_spec.rb",
    "spec/controllers/admin/redirects_controller_spec.rb",
    "spec/controllers/admin/sites_controller_spec.rb",
    "spec/controllers/pages_controller_spec.rb",
    "spec/models/nav_item_spec.rb",
    "spec/models/page_spec.rb",
    "spec/models/redirect_spec.rb",
    "spec/models/site_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/site_logic.rake"
  ]
  s.homepage = "http://github.com/ivanoblomov/site_logic"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "An engine for search-engine-optimized content management."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<carrierwave-mongoid>, [">= 0"])
      s.add_runtime_dependency(%q<ckeditor>, [">= 0"])
      s.add_runtime_dependency(%q<mini_magick>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid-tree>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.1"])
      s.add_runtime_dependency(%q<rmagick>, ["= 2.12.2"])
      s.add_runtime_dependency(%q<scaffold_logic>, [">= 0"])
      s.add_runtime_dependency(%q<stringex>, [">= 0"])
      s.add_runtime_dependency(%q<tanker>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<carrierwave-mongoid>, [">= 0"])
      s.add_dependency(%q<ckeditor>, [">= 0"])
      s.add_dependency(%q<mini_magick>, [">= 0"])
      s.add_dependency(%q<mongoid-tree>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.1"])
      s.add_dependency(%q<rmagick>, ["= 2.12.2"])
      s.add_dependency(%q<scaffold_logic>, [">= 0"])
      s.add_dependency(%q<stringex>, [">= 0"])
      s.add_dependency(%q<tanker>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<carrierwave-mongoid>, [">= 0"])
    s.add_dependency(%q<ckeditor>, [">= 0"])
    s.add_dependency(%q<mini_magick>, [">= 0"])
    s.add_dependency(%q<mongoid-tree>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.1"])
    s.add_dependency(%q<rmagick>, ["= 2.12.2"])
    s.add_dependency(%q<scaffold_logic>, [">= 0"])
    s.add_dependency(%q<stringex>, [">= 0"])
    s.add_dependency(%q<tanker>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

