# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{site_logic}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bantik"]
  s.date = %q{2010-11-19}
  s.description = %q{An engine for search-engine-optimized content management.}
  s.email = %q{corey@seologic.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/application_controller.rb",
    "app/helpers/application_helper.rb",
    "app/views/layouts/application.html.erb",
    "config.ru",
    "config/application.rb",
    "config/boot.rb",
    "config/database.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/test.rb",
    "config/initializers/backtrace_silencers.rb",
    "config/initializers/inflections.rb",
    "config/initializers/mime_types.rb",
    "config/initializers/secret_token.rb",
    "config/initializers/session_store.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "db/seeds.rb",
    "doc/README_FOR_APP",
    "lib/site_logic.rb",
    "log/development.log",
    "log/production.log",
    "log/server.log",
    "log/test.log",
    "public/404.html",
    "public/422.html",
    "public/500.html",
    "public/favicon.ico",
    "public/images/rails.png",
    "public/index.html",
    "public/javascripts/application.js",
    "public/javascripts/controls.js",
    "public/javascripts/dragdrop.js",
    "public/javascripts/effects.js",
    "public/javascripts/prototype.js",
    "public/javascripts/rails.js",
    "public/robots.txt",
    "public/stylesheets/.gitkeep",
    "script/rails",
    "spec/site_logic_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "test/performance/browsing_test.rb",
    "test/test_helper.rb",
    "vendor/plugins/.gitkeep"
  ]
  s.homepage = %q{http://github.com/Bantik/site_logic}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An engine for search-engine-optimized content management.}
  s.test_files = [
    "spec/site_logic_spec.rb",
    "spec/spec_helper.rb",
    "test/performance/browsing_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta.17"])
      s.add_runtime_dependency(%q<rails>, ["= 3.0.1"])
      s.add_runtime_dependency(%q<scaffold_logic>, [">= 0"])
      s.add_runtime_dependency(%q<tiny_mce>, [">= 0"])
      s.add_development_dependency(%q<be_valid_asset>, [">= 0"])
      s.add_development_dependency(%q<capybara>, [">= 0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<faker>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<launchy>, [">= 0"])
      s.add_development_dependency(%q<machinist_mongo>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<spork>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.17"])
      s.add_dependency(%q<rails>, ["= 3.0.1"])
      s.add_dependency(%q<scaffold_logic>, [">= 0"])
      s.add_dependency(%q<tiny_mce>, [">= 0"])
      s.add_dependency(%q<be_valid_asset>, [">= 0"])
      s.add_dependency(%q<capybara>, [">= 0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<faker>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<launchy>, [">= 0"])
      s.add_dependency(%q<machinist_mongo>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<spork>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.17"])
    s.add_dependency(%q<rails>, ["= 3.0.1"])
    s.add_dependency(%q<scaffold_logic>, [">= 0"])
    s.add_dependency(%q<tiny_mce>, [">= 0"])
    s.add_dependency(%q<be_valid_asset>, [">= 0"])
    s.add_dependency(%q<capybara>, [">= 0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<faker>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<launchy>, [">= 0"])
    s.add_dependency(%q<machinist_mongo>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<spork>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

