defaults: &defaults
  host: localhost
  autocreate_indexes: false
  allow_dynamic_fields: false
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3
  skip_version_check: true

development:
  <<: *defaults
  database: site_logic_development

test:
  <<: *defaults
  database: site_logic_test

